### ISSUE TITLE
error when using the transform function on the model with n_components > 2

### ISSUE THREAD

**Issue by sbashett** [arturjordao/IncrementalDimensionalityReduction#1]
Hello, I am testing the IPLS and CIPLS methods from your codebase and it throws an error when using the transform function after model fit with n_components > 2. Error can be replicated by running the binary_classification.py script with n_components > 2.

**Comment by arturjordao** [comment]
Dear @sbashett,

First of all, my apologies for the delay (seven months ago) in replying to your issue.

This error is due to numerical instability when employing many components. Such instability is the major limitation of CIPLS and IPLS as well. It turns out that during the algebraic decomposition ([Equation 4.2](https://arxiv.org/pdf/1910.02319.pdf)) of the first components the numbers become extremely small leading to unstable computation that is propagated and accumulated to higher-order components. We observe these issues mainly when using features from deep networks, which often present high numerical precision (32-bit floating point representation). Moreover, we note that IPLS exhibited even worse numerical instability.

If you have any other questions, please let me know. Once again, apologies for the delay. 

ps: Add my GitHub user (@arturjodao) when creating an issue; thus, I will be notified by email.
